# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/semc/shakira/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/semc/shakira/proprietary/app/Camera.apk:system/app/Camera.apk \
    vendor/semc/shakira/proprietary/app/FileManager.apk:system/app/FileManager.apk \
    vendor/semc/shakira/proprietary/app/MusicFX.apk:system/app/MusicFX.apk \
    vendor/semc/shakira/proprietary/app/QuickSearchBox.apk:system/app/QuickSearchBox.apk \
    vendor/semc/shakira/proprietary/app/Superuser.apk:system/app/Superuser.apk \
    vendor/semc/shakira/proprietary/app/SystemConnector.apk:system/app/SystemConnector.apk
	
PRODUCT_COPY_FILES += \
    vendor/semc/shakira/proprietary/bin/akmd2:system/bin/akmd2 \
    vendor/semc/shakira/proprietary/bin/chargemon:system/bin/chargemon \
    vendor/semc/shakira/proprietary/bin/hciattach:system/bin/hciattach \
    vendor/semc/shakira/proprietary/bin/inputattach:system/bin/inputattach \
    vendor/semc/shakira/proprietary/bin/nvimport:system/bin/nvimport \
    vendor/semc/shakira/proprietary/bin/port-bridge:system/bin/port-bridge \
    vendor/semc/shakira/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/semc/shakira/proprietary/bin/semc_chargalg:system/bin/semc_chargalg \
    vendor/semc/shakira/proprietary/bin/slidercounter:system/bin/slidercounter \
    vendor/semc/shakira/proprietary/bin/updatemiscta:system/bin/updatemiscta \
    vendor/semc/shakira/proprietary/bin/wlan_cu:system/bin/wlan_cu \
    vendor/semc/shakira/proprietary/bin/wlan_loader:system/bin/wlan_loader
	
PRODUCT_COPY_FILES += \
    vendor/semc/shakira/etc/apns-conf.xml:system/etc/apns-conf.xml \
    vendor/semc/shakira/etc/AudioFilter.csv:system/etc/AudioFilter.csv \
    vendor/semc/shakira/etc/AutoVolumeControl.txt:system/etc/apns-conf.xml \
    vendor/semc/shakira/etc/gps.conf:system/etc/gps.conf \
    vendor/semc/shakira/etc/hw_config.sh:system/etc/hw_config.sh \
    vendor/semc/shakira/etc/media_profiles.xml:system/etc/sensors.conf \
    vendor/semc/shakira/etc/sensors.conf:system/etc/sensors.conf \
    vendor/semc/shakira/etc/sysctl.conf:system/etc/sysctl.conf
	
PRODUCT_COPY_FILES += \
    vendor/semc/shakira/etc/firmware/fm_rx_init_1273.1.bts:system/etc/firmware/fm_rx_init_1273.1.bts \
    vendor/semc/shakira/etc/firmware/fm_rx_init_1273.2.bts:system/etc/firmware/fm_rx_init_1273.2.bts \
    vendor/semc/shakira/etc/firmware/fm_tx_init_1273.1.bts:system/etc/firmware/fm_tx_init_1273.1.bts \
    vendor/semc/shakira/etc/firmware/fm_tx_init_1273.2.bts:system/etc/firmware/fm_tx_init_1273.2.bts \
    vendor/semc/shakira/etc/firmware/fmc_init_1273.1.bts:system/etc/firmware/fmc_init_1273.1.bts \
    vendor/semc/shakira/etc/firmware/fmc_init_1273.2.bts:system/etc/firmware/fmc_init_1273.2.bts \
    vendor/semc/shakira/etc/firmware/TIInit_7.2.31.bts:system/etc/firmware/TIInit_7.2.31.bts \
    vendor/semc/shakira/etc/firmware/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
    vendor/semc/shakira/etc/firmware/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw
	
PRODUCT_COPY_FILES += \
    vendor/semc/shakira/etc/init.d/01sysctl:system/etc/init.d/01sysctl \
    vendor/semc/shakira/etc/init.d/04modules:system/etc/init.d/04modules \
    vendor/semc/shakira/etc/init.d/20userinit:system/etc/init.d/20userinit \
    vendor/semc/shakira/etc/init.d/99complete:system/etc/init.d/99complete
	
PRODUCT_COPY_FILES += \
    vendor/semc/shakira/etc/semc/chargemon/anim1.rle:system/etc/semc/chargemon/anim1.rle \
    vendor/semc/shakira/etc/semc/chargemon/anim2.rle:system/etc/semc/chargemon/anim2.rle \
    vendor/semc/shakira/etc/semc/chargemon/anim3.rle:system/etc/semc/chargemon/anim3.rle \
    vendor/semc/shakira/etc/semc/chargemon/anim4.rle:system/etc/semc/chargemon/anim4.rle \
    vendor/semc/shakira/etc/semc/chargemon/anim5.rle:system/etc/semc/chargemon/anim5.rle \
    vendor/semc/shakira/etc/semc/chargemon/anim6.rle:system/etc/semc/chargemon/anim6.rle \
    vendor/semc/shakira/etc/semc/chargemon/anim7.rle:system/etc/semc/chargemon/anim7.rle \
    vendor/semc/shakira/etc/semc/chargemon/anim8.rle:system/etc/semc/chargemon/anim8.rle
	
PRODUCT_COPY_FILES += \
    vendor/semc/shakira/etc/wifi/dnsmasq.conf:system/etc/wifi/dnsmasq.conf \
    vendor/semc/shakira/etc/wifi/tiwlan.ini:system/etc/wifi/tiwlan.ini \
    vendor/semc/shakira/etc/wifi/tiwlan_firmware.bin:system/etc/wifi/tiwlan_firmware.bin
	
PRODUCT_COPY_FILES += \
    vendor/semc/shakira/lib/libaudioeq.so:system/lib/libaudioeq.so \
    vendor/semc/shakira/lib/libauth.so:system/lib/libauth.so \
    vendor/semc/shakira/lib/libcm.so:system/lib/libcm.so \
    vendor/semc/shakira/lib/libdiag.so:system/lib/libdiag.so \
    vendor/semc/shakira/lib/libdll.so:system/lib/libdll.so \
    vendor/semc/shakira/lib/libdsm.so:system/lib/libdsm.so \
    vendor/semc/shakira/lib/libdss.so:system/lib/libdss.so \
    vendor/semc/shakira/lib/libFLAC.so:system/lib/libFLAC.so \
    vendor/semc/shakira/lib/libgsdi_exp.so:system/lib/libgsdi_exp.so \
    vendor/semc/shakira/lib/libgsl.so:system/lib/libgsl.so \
    vendor/semc/shakira/lib/libgstk_exp.so:system/lib/libgstk_exp.so \
    vendor/semc/shakira/lib/libmemalloc.so:system/lib/libmemalloc.so \
    vendor/semc/shakira/lib/libmiscta.so:system/lib/libmiscta.so \
    vendor/semc/shakira/lib/libmm-adspsvc.so:system/lib/libmm-adspsvc.so \
    vendor/semc/shakira/lib/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    vendor/semc/shakira/lib/libmmipl.so:system/lib/libmmipl.so \
    vendor/semc/shakira/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/semc/shakira/lib/libnv.so:system/lib/libnv.so \
    vendor/semc/shakira/lib/liboem_rapi.so:system/lib/liboem_rapi.so \
    vendor/semc/shakira/lib/libOmxAacDec.so:system/lib/libOmxAacDec.so \
    vendor/semc/shakira/lib/libOmxAacEnc.so:system/lib/libOmxAacEnc.so \
    vendor/semc/shakira/lib/libOmxAmrDec.so:system/lib/libOmxAmrDec.so \
    vendor/semc/shakira/lib/libOmxAmrEnc.so:system/lib/libOmxAmrEnc.so \
    vendor/semc/shakira/lib/libOmxAmrRtpDec.so:system/lib/libOmxAmrRtpDec.so \
    vendor/semc/shakira/lib/libOmxAmrwbDec.so:system/lib/libOmxAmrwbDec.so \
    vendor/semc/shakira/lib/libOmxEvrcDec.so:system/lib/libOmxEvrcDec.so \
    vendor/semc/shakira/lib/libOmxEvrcEnc.so:system/lib/libOmxEvrcEnc.so \
    vendor/semc/shakira/lib/libOmxH264Dec.so:system/lib/libOmxH264Dec.so \
    vendor/semc/shakira/lib/libOmxMp3Dec.so:system/lib/libOmxMp3Dec.so \
    vendor/semc/shakira/lib/libOmxMpeg4Dec.so:system/lib/libOmxMpeg4Dec.so \
    vendor/semc/shakira/lib/libOmxQcelp13Enc:system/lib/libOmxQcelp13Enc \
    vendor/semc/shakira/lib/libOmxQcelpDec.so:system/lib/libOmxQcelpDec.so \
    vendor/semc/shakira/lib/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \
    vendor/semc/shakira/lib/libOmxWmaDec.so:system/lib/libOmxWmaDec.so \
    vendor/semc/shakira/lib/libOmxWmvDec.so:system/lib/libOmxWmvDec.so \
    vendor/semc/shakira/lib/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/semc/shakira/lib/libopencore_common.so:system/lib/libopencore_common.so \
    vendor/semc/shakira/lib/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/semc/shakira/lib/libQcomUI.so:system/lib/libQcomUI.so \
    vendor/semc/shakira/lib/libqmi.so:system/lib/libqmi.so \
    vendor/semc/shakira/lib/libqueue.so:system/lib/libqueue.so \
    vendor/semc/shakira/lib/libril.so:system/lib/libril.so \
    vendor/semc/shakira/lib/librpc.so:system/lib/librpc.so \
    vendor/semc/shakira/lib/libsemc_ril.so:system/lib/libsemc_ril.so \
    vendor/semc/shakira/lib/libsurfaceflinger.so:system/lib/libsurfaceflinger.so \
    vendor/semc/shakira/lib/libsystemconnector_hal_jni.so:system/lib/libsystemconnector_hal_jni.so \
    vendor/semc/shakira/lib/libuim.so:system/lib/libuim.so \
    vendor/semc/shakira/lib/libwms.so:system/lib/libwms.so \
    vendor/semc/shakira/lib/libwmsts.so:system/lib/libwmsts.so
	
PRODUCT_COPY_FILES += \
    vendor/semc/shakira/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/semc/shakira/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/semc/shakira/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/semc/shakira/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so
	
PRODUCT_COPY_FILES += \
    vendor/semc/shakira/lib/hw/audio.primary.delta.so:system/lib/hw/audio.primary.delta.so \
    vendor/semc/shakira/lib/hw/audio_policy.delta.so:system/lib/hw/audio_policy.delta.so \
    vendor/semc/shakira/lib/hw/copybit.delta.so:system/lib/hw/copybit.delta.so \
    vendor/semc/shakira/lib/hw/gps.delta.so:system/lib/hw/gps.delta.so \
    vendor/semc/shakira/lib/hw/gralloc.delta.so:system/lib/hw/gralloc.delta.so \
    vendor/semc/shakira/lib/hw/hal_seport.default.so:system/lib/hw/hal_seport.default.so \
    vendor/semc/shakira/lib/hw/lights.delta.so:system/lib/hw/lights.delta.so \
    vendor/semc/shakira/lib/hw/sensors.delta.so:system/lib/hw/sensors.delta.so
	
PRODUCT_COPY_FILES += \
    vendor/semc/shakira/lib/libsystemconnector/libuinputdevicejni.so:system/lib/libsystemconnector/libuinputdevicejni.so
	
PRODUCT_COPY_FILES += \
    vendor/semc/shakira/media/bootanimation.zip:system/media/bootanimation.zip
	
PRODUCT_COPY_FILES += \
    vendor/semc/shakira/usr/idc/synaptics-rmi-touchscreen.idc:system/usr/idc/synaptics-rmi-touchscreen.idc \
    vendor/semc/shakira/usr/idc/cyttsp-spi.idc:system/usr/idc/cyttsp-spi.idc \
    vendor/semc/shakira/usr/keychars/shakira_keypad.kcm.bin:system/usr/keychars/shakira_keypad.kcm.bin \
    vendor/semc/shakira/usr/keychars/systemconnector.kcm.bin:system/usr/keychars/systemconnector.kcm.bin \
    vendor/semc/shakira/usr/keylayout/7k_handset.kl:system/usr/keylayout/7k_handset.kl \
    vendor/semc/shakira/usr/keylayout/h2w_headset.kl:system/usr/keylayout/h2w_headset.kl \
    vendor/semc/shakira/usr/keylayout/shakira_keypad.kl:system/usr/keylayout/shakira_keypad.kl \
    vendor/semc/shakira/usr/keylayout/systemconnector.kl:system/usr/keylayout/systemconnector.kl